name: stampcamera # ✅ DEJAR IGUAL
description: "Aplicación de inspección vehicular para A&G Ajustadores" # ✅ CAMBIAR ESTA
publish_to: "none" # ✅ DEJAR IGUAL
version: 1.3.8+33

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  image: ^4.5.4
  flutter_image_compress: ^2.3.0
  intl: ^0.20.2
  share_plus: ^11.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  flutter_riverpod: ^2.6.1
  go_router: ^16.0.0
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  mobile_scanner: ^7.0.1
  geolocator: ^14.0.2
  image_picker: ^1.1.2
  connectivity_plus: ^6.1.4
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  geocoding: ^4.0.0
  path: ^1.9.1
  in_app_update: ^4.2.3
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

flutter:
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
  assets:
    - assets/logo.png
    - assets/splash/logo_blanco.png
    - assets/splash/branding.png
    - assets/icon/icon.png
    - assets/logo_principal.png
    - assets/splash/splash_ilustracion_persona.png
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#0A2D3E" # Azul oscuro como en la imagen subida
  image: assets/splash/logo_blanco.png
  android: true

  android_12:
    image: assets/splash/logo_blanco.png
    color: "#0A2D3E"
    branding: assets/splash/branding.png
